name: Build and release Docker images
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Determine latest version
        id: latest_version
        uses: flownative/action-git-latest-release@v1

      - run: |
          sudo chmod -R ugo+rwX . && shopt -s dotglob && rm -rf *

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.latest_version.outputs.tag }}
          fetch-depth: 100

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=true
          images: |
            flownative/action-helm-release
          labels: |
            org.opencontainers.image.version=${{ steps.latest_version.outputs.version }}
          tags: |
            type=semver,pattern={{major}},value=${{ steps.latest_version.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.latest_version.outputs.version }}
            type=semver,pattern={{version}},value=${{ steps.latest_version.outputs.version }}

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
